### ISSUE TITLE
Relative font-size support

### ISSUE THREAD

**Issue by andriytyurnikov** [stormwarning/tailwindcss-capsize#212]
I am exploring some approaches to responisve typography, and I am trying to use tricks like 

```CSS
.rescale-from-rem {
  font-size: calc(100% / 1.428);
}

.autoscaled-base {
  font-size: calc(1rem / 4 * 8);
}

```
Which results in 
```CSS
--font-size-px: NaN
```

I am not sure, what is going on here. Is implementation somehow reliant on pixel values?
